### PR TITLE
feat(challenge): add challenge schema

### LINKED ISSUE #3: Create challenge schema
Schema:
 *  - description
 *  - hashtag
 *  - url
 *  - lang
 *  - type
 *  - deleted
 *  - reportCount

### PR DESCRIPTION
**Pull request by namadnuno**
Closes #3

### CODE REVIEW

**Comment by namadnuno** [comment]
> nice job 👍 what about creating an enum for the lang/type?

I thought of that, but the only way is assign it to a string and set the enum prop, do you agree?
(docs: https://mongoosejs.com/docs/schematypes.html#schematype-options)

**Comment by namadnuno** [comment]
can you provide a list of types and langs?

**Comment by rbgoncalves** [comment]
We could explore all these validators, but honestly, I already have all these validations running in the app so

**Comment by namadnuno** [comment]
> We could explore all these validators, but honestly, I already have all these validations running in the app so

All right but anyway it is a good way of creating constrains and reduce the future integrations errors

**Pull request merged**
